---
# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes

# Configure PostgreSQL.
- include: initialize.yml
- include: databases.yml
- include: users.yml
