---
- name: Ensure PostgreSQL Python libraries are installed.
  apt: "name=python-psycopg2 state=installed"

- name: Ensure PostgreSQL packages are installed.
  apt: "name={{ item }} state=installed"
  with_items: "{{ postgresql_packages }}"
